name: 'Ngrok TCP Tunelling'
description: 'A github action for tunelling TCP traffic from within Workflow environemt'

branding:
  icon: 'activity'  
  color: 'green'

inputs:
  timeout:  
    description: 'Deployment timeout before closing it down'
    required: true
    default: '1h'
  port:
    description: 'The port to forward HTTP traffic to'
    required: true
  ngrok_authtoken:
    description: 'Ngrok authorization token'
    required: true

runs:
  using: "composite"
  steps: 
    - run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
      shell: bash
    - run: unzip -qq ngrok-v3-stable-linux-amd64.zip
      shell: bash
    - run: ./ngrok config add-authtoken ${{ inputs.ngrok_authtoken }}
      shell: bash
    - run: timeout ${{ inputs.timeout }} ./ngrok http ${{ inputs.port }} --log=stdout
      shell: bash
